# Generated by Django 3.0 on 2020-10-04 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chatgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.ChatGroup'),
            preserve_default=False,
        ),
    ]
