# Generated by Django 3.0 on 2020-10-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201014_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='blob',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
