# Generated by Django 3.0 on 2020-10-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
