# Generated by Django 3.0.7 on 2020-10-23 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201023_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.TextField(default=django.utils.timezone.now),
        ),
    ]
